_target_: data.BDD100KDataset
images_dir: "data/bdd100k/images/10k/train"
labels_dir: "data/bdd100k/labels/sem_seg/masks/train"
det_train_path: "data/bdd100k/labels/det_20/det_train.json"
det_val_path: "data/bdd100k/labels/det_20/det_val.json"
train_ratio: 0.7
test_ratio: 0.1
val_ratio: 0.2
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.3654, 0.4002, 0.4055]
      std: [0.2526, 0.2644, 0.2755]

target_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]
      interpolation: 0
    - _target_: data.utils.ConvertToLongTensor
    - _target_: data.utils.RemapClasses
      old_to_new:
        0: 0
        2: 1
        8: 2
        10: 3
        13: 4

batch_size: 16
class_weights_file: "data/class_weights.pt"
