_target_: data.BDD100KDataset
images_dir: "data/bdd100k/images/10k/train"
labels_dir: "data/bdd100k/labels/sem_seg/masks/train"
det_train_path: "data/bdd100k/labels/det_20/det_train.json"
det_val_path: "data/bdd100k/labels/det_20/det_val.json"
test_size: 400
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.3654, 0.4002, 0.4055] # metrics calculated on train partition
      std: [0.2526, 0.2644, 0.2755] # metrics calculated on train partition
target_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]
      interpolation: 0
    - _target_: data.utils.ConvertToLongTensor
batch_size: 16
class_weights_file: "data/class_weights.pt"