defaults:
  - _self_
  - trainer: default
  - dataset: bdd100k
  - optimizer: adam
  - experiment: unet_baseline

run_name: "example_run"
epochs: 100
seed: 1337
device: "cuda"

verbose: true

criterion:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: 255
